spring:
  thymeleaf:
    cache: true
server:
  port: 8085
  tomcat:
    accept-count: 500
    max-threads: 500
    min-spare-threads: 300
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/javascript,text/css,text/plain,application/json
redis:
      poolMaxIdle: 500
      poolMaxTotal: 1000
swagger:
    swaggerSwitch: true
#logging:
#  file:
#    max-history: 2
#    max-size: 10MB
#  path: c:/Users/T011689/prod
#  pattern: ${LOG_PATH}.%d{yyyy-MM-dd}.log
