spring:
  servlet:
    multipart:
      max-file-size: 10MB
  dubbo:
    server: true
  application:
    name: demo
  datasource:
    url: jdbc:mysql://47.94.105.130:3306/spring-security?useSSL=false&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: ZHAODONGqwe123!@#
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    encoding: utf-8
    mode: HTML5
    suffix: .html
  profiles:
    active: dev
  resources:
    cache:
      cachecontrol:
        max-age: 60
#  rabbitmq:
#    addresses: 47.94.105.130
#    username: admin
#    password: P@ssw0rd
#    virtual-host: /
##    publisher-confirms: true
##    publisher-returns: true
##    template:
##      mandatory: true
#    listener:
#      simple:
#        acknowledge-mode: auto
#        prefetch: 250
#        concurrency: 4
#        max-concurrency: 20
mybatis:
  mapper-locations: classpath:mapper/*.xml
#logging:
#  level.com.example.demo.dao: debug
fdfs:
  connect-timeout: 600
  so-timeout: 1500
  tracker-list: 172.17.244.159:22122
  thumb-image:             #缩略图生成参数
      width: 150
      height: 150
fastDfs:
  host: http://47.94.105.130:8888/
redis:
  host: 127.0.0.1
  port: 6379
  timeout: 10
pagehelper:
  reasonable: true
  support-methods-arguments: false
  helper-dialect: mysql
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 2048
web:
  img-path: C:/images/

